from fastapi import FastAPI, Request
import random
import string

app = FastAPI()

@app.middleware("http")
async def request_id_logging(request: Request, call_next):
    """
    A function call_next that will receive the request as a parameter.
    This function will pass the request to the corresponding path operation.
    Then it returns the response generated by the corresponding path operation.
    """
    response = await call_next(request)
    random_letters = ''.join(random.choice(string.ascii_letters) for _ in range(10))
    print(f"Log {random_letters}")
    response.headers["X-Request-ID"] = random_letters
    return response


@app.get("/")
async def say_hi():
    return "Hello"